### ISSUE TITLE
Fix render transform bug related to rendering ray traced result

### ISSUE THREAD

**Issue by StewStrong** [ValkyrienSkies/Valkyrien-Skies-2#23]
This can easily be seen when placing a sign on a ship, note that the text renders incorrectly unless the player is selecting a block on a ship. This implies that the issue with render transforms is related to how we render the block outline of selected blocks.

**Comment by ewoudje** [comment]
So for more info since i checked for it but as far as i can tell there shouldn't be anything wrong with the block outlines;
And the weird thing is that the sign itself *does* get rendered (on the correct position) but the text is flying all around in the world (still gets rendered)
The only reason i can think of that this can happen is that between the rendering of the sign itself and text something happens

**Comment by StewStrong** [comment]
I'm not sure how, but this seems to have fixed itself. I'm unable to reproduce this issue anymore with signs or entities.

**Comment by StewStrong** [comment]
Fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/5c303ee86676772eb77b30feeda7356b82ac757d
