### ISSUE TITLE
Crash on startup with only Quilt and Valkrien Skies installed.

### ISSUE THREAD

**Issue by Aquaeyes** [ValkyrienSkies/Valkyrien-Skies-2#257]
Mods:
qfapi-1.0.0-beta.28_qsl-1.1.0-beta.26_fapi-0.67.0_mc-1.18.2
valkyrienskies-118-fabric-2.1.0-beta1+0c28d02ed5

Logs:
_Latest_: https://mclo.gs/FL66dnM

Key section for searching:
[20:08:09] [main/ERROR]: Minecraft has crashed!
org.quiltmc.loader.impl.FormattedException: java.lang.LinkageError: loader constraint violation: loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @6dd7b5a3 wants to load interface org.slf4j.Logger. A different interface with the same name was previously loaded by 'app'. (org.slf4j.Logger is in unnamed module of loader 'app')

**Comment by Rubydesic** [comment]
Yea I asked in quilt discord why this happens and no one knows.

**Comment by unilock** [comment]
Does the crash occur when using [Fabric API](https://modrinth.com/mod/fabric-api) instead of QFAPI? It could be an issue with Quilt Loader itself rather than QFAPI.
Also, could you try with Java 17 instead of 19? I don't know if it's relevant, but since the former is what's (usually) tested against, it'd at least give us a baseline to work off of.

**Comment by Aquaeyes** [comment]
Same issue occurs on Java 17, and with Fabric API instead of QFAPI :(

**Comment by Rubydesic** [comment]
fixed in latest quilt 0.18
