### ISSUE TITLE
Completely redo the networking code

### ISSUE THREAD

**Issue by StewStrong** [ValkyrienSkies/Valkyrien-Skies-2#29]
The networking code we have now is totally sub-optimal, and only sends updates 20 times a second (60 times would be ideal). It lags the game once more than like 50 ships have been spawned.

We also want to use UDP if possible instead of TCP, since we don't really care if we lose a position update packet, since we can just get the information from the next packet.

**Comment by Rubydesic** [comment]
note: most of the lag is caused by the extremely inefficient code that sends every single ship, in full, to the client every single tick. UDP will only improve performance on flaky network connections.

Further info on UDP:

## For negotiating a UDP connection

1. Try connecting on UDP through the same port that the TCP connection is established. Most server hosts have both UDP and TCP open.
2. Try using the TCP connection to negotiate a UDP connection through hole punching
3. If any of the above succeed, upgrade the UDP channel (and therefore any packets sent over it, like ship transform) to actually use UDP instead of being relayed over TCP.

## Send rate

Ideally we want some kind of congestion control that will automatically decrease update send rate if the bandwidth is too low. 

## Sequence ID

UDP has no guaranteed order so each transform update packet will need to have a sequence number on it so the client doesn't overwrite newer transforms with older ones.

**Comment by Rubydesic** [comment]
more notes:

## Ship Loading

When a chunk enters a players load distance do the following:

1. If the ship the chunk belongs to is unloaded, queue it to be loaded
2. If/when the chunk is loaded, check if the player has the ship loaded. If not, send the ship to the player.
3. Send a chunk watch task

When a chunk exits a players unload distance do the following:

1. If the ship the chunk belongs to has no more chunks loaded, queue it to be unloaded
2. Check if the player has any more chunks on the ship loaded. If not, tell the player to unload the ship
3. Send chunk unwatch task

## Chunk Unwatch Tasks

We don't send them wtf! Send some chunk unwatch tasks so the client doesn't forever have chunks loaded.
