### ISSUE TITLE
Hopper minecarts do not render (forge 1.18)

### ISSUE THREAD

**Issue by walksanatora** [ValkyrienSkies/Valkyrien-Skies-2#333]
i placed minecrarts with hoppers on rails, but they do not render but i can still open their inventories

**Comment by walksanatora** [comment]
as noted by @Ch1215 
> Normal, Chest and TNT Minecarts dont render, but are interactable, Minecarts from other mods (Minecart with jukeboxes from etched and Create: Steam and Rails, along with Minecart with Dispenser from supplementaries) DO render

**Comment by Ch1216** [comment]
Clockwork fixes this issues, also to update my previous note, its not that Minecarts from other mods rendered while vanilla ones don't, Rather is that when I placed them onto rails in ships, they spawned in the real world rather than in the ship, though weirdly, they were  aligned to the ship tracks, while not being attached to them
should i new issue be made for the minecarts from other mods bug?

**Comment by thetheaplant** [comment]
Unable to recreate.
