### ISSUE TITLE
Unable to launch MC in my custom modpack

### ISSUE THREAD

**Issue by trueblue222** [ValkyrienSkies/Valkyrien-Skies-2#339]
Just crashes to the launcher with exit code 1

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10418458/latest.log)

**Comment by SrRapero720** [comment]
Quick note: Logs are useless because only show up whats get loaded (no more info) 
so next time open file and if you no found any info related to mod, then send also debug.log

Now, idk why but that happens with Minecraft Default's launcher, try to use another launcher temporally (i highly recomend sklauncher)

**Comment by Rubydesic** [comment]
install kotlin for forge
