### ISSUE TITLE
Invisible ships + frozen player

### ISSUE THREAD

**Issue by oliverrook** [ValkyrienSkies/Valkyrien-Skies-2#357]
What it says in the title. Currently using a lot of mods, will try and narrow it down a bit when I can.

But I seem to not just have invisible ships, but when I assemble them my character becomes frozen in place but can still look around and interact with nearby blocks that weren't part of the ship. Additionally, it treats my character as if they were flying, meaning that block breaking is incredibly slow.

I am not using optifine, I am using oculus + rubidium.

Edit: Additionally, the reason I haven't posted a log is because I took a look myself and there isn't anything besides saves and backups for the entire duration of my testing this bug and recreating it. There are no errors or warnings mentioned after the world loads in, nor when I assemble the ship or use commands to teleport out of the freeze.

**Comment by UrbanSide** [comment]
If you are using the mod as Immersive Portals, disable it.  This mod is not yet compatible with VS/Eureka.

**Comment by StonedGoat** [comment]
BUMP, IM HAVING THE SAME ISSUE, PLEASE!!

[Server] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8657651650000006E7, 121.0, 771.6990397165284] -> [824.4758023291366, 135.14802317945257, 1.2290050650000006E7] returning empty list! this might break things

This error may be related. PLEASE Dev!!

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS, addons, and one other mod, and then create a new issue

**Comment by StonedGoat** [comment]
Actually, I forgot to mention something that might be extremely important.
(Also I'm sorry if I felt bothersome at all)

I THINK I know what is sourcing this conflict in the first place. Like the person who made this original post, I'm using Rubidium.

I discovered Rubidium has a rare bug that causes chunks to turn invisible, and I haven't discovered the exact /cause/, but I found a "fix" for it. This "fix" is to simply disable "chunk rendering mix in" in rubidium's properties config file, by adding this line of text: mixin.features.chunk_rendering=false

This appears to be the 'cause' of this but.. I don't know how to fix it without leaving my chunks invisible, it's either chunks are invisible, or everyone using this 'fix' gets stuck on logging in, on top of ships being invisible and non-collisable, as well as some of them causing players to become immobile upon entering their chunks. This applies regardless to players upon logging in, no matter where they are relative to the ships. I'm sorry to pester and prod on someone else's post, 

I don't know if this will help at all, I know the visual chunk error is on rubidium's end, but this appears to be a potential conflict between rubidium and VS together. Which.. is a very unfortunate issue because they're both very popular mods. 

Do you have ANY idea how to fix this somehow on the client's end without having to just re-enable rubidium's mixin feature? :( 
I've even tried switching to Embeddium instead but that resulted in the chunk error returning regardless of the setting I used.

I'm really sorry to pester on another person's post, but i'm having this exact same issue as this person, and I'm helping host a small community and this is a serious problem I'm struggling to resolve :S

**Comment by PriestOfFerns** [comment]
@StonedGoat 
You probably shouldn't really be using rubidium in the first place, since embeddium is mostly just better and has better compat with VS2 anyway,

**Comment by PriestOfFerns** [comment]
@StonedGoat 
Also if you want your issue to get fixed, providing a modpack and log would be helpful, instead of vague assertions about what you think is happening

**Comment by StonedGoat** [comment]
honestly not sure why i never posted logs, i could swear i did. 

despite this, i'm fully certain MY specific end of this issue was due to setting "mixin.features.chunk_rendering" to false.

however this doesn't really "fix" the existing problem, if this has occurred in the past. regardless, my issue was sourced from the mixin rendering.

im also not sure the devs here are very active or willing to solve things, im now thoroughly looking into an unrelated MAJOR lag spike issue that everything is pointing to VS Create entities, and.. like, theres issues on that subject EVERYWHERE. theres people having these lag spikes from entities not even EXISTING.

The devs barely touched any of them, and the only responses I've seen is "it'll be fixed soonish" over 6 months ago.

its awful to see honestly.

as for embeddium vs rubidium, i didn't choose to use rubidium personally, it was included in our pack, and i don't know what the decision behind it was. i did try switching to embeddium as i said, but.. yknow, that did nOTHING for the problem so..

i dont think you can put it any other way, VS2 has compatibility issues, badly. and it's not like it's just one or two mods, i've been seeing countless issues lately..

**Comment by RomkaBro1** [comment]
this bug still appears in mp
no choice but to remove embeddium

**Comment by blockninja124** [comment]
Valkyrien Skies is fully compatible with Embeddium. This is not a conflict issue (as far as I know), it is simply a bug with VS 2.4.8 on its own. You can wait for it to be fixed, or join a singleplayer world first before joining a server to get around it.
