### ISSUE TITLE
Issue with Magma server "Too Many Physics"

### ISSUE THREAD

**Issue by Chisasfam** [ValkyrienSkies/Valkyrien-Skies-2#430]
On my modded factions server, I have this mod, with eureka ships and Create of course, and some others like MineColonies. and ive recently ran into an issue after switching to a magma server from forge because I want plugins, the server will crash and then spam the console with this when I try to restart it 
![frames](https://user-images.githubusercontent.com/127439502/224125757-e3e2c892-40b9-44f8-9271-bdb6ad1b7ebb.PNG)
whats going on? and how can I fix?

**Comment by Lendill** [comment]
I´m not the mod developer -but magma had some issues for me too (not with this mod, but in general) maybe try arclight instead :)

**Comment by ThePlasticPotato** [comment]
Magma is incompatible with VS2 for the time being- this is known on our end, and I think known on theirs. Use Arclight for the time being.

**Comment by unilock** [comment]
I have the exact same issue *without* Magma, or any other Bukkit-on-Forge mods. In my case, it's likely because I have approximately 500 mods installed on my own private modpack ([mod list](https://gist.github.com/unilock/79ac54321a731426092679778234b5c1)).
I, personally, am not too concerned about this issue at the moment, since I intend to remove the majority of those mods "soon", which should hopefully be rid of the problem.
Though if you'd like me to test with what I have now, I certainly can. In any case, I'll definitely report back if I continue running into this problem later.

Of note: I usually run into what the OP describes - that is, the server crashing after the repeated "Too many frames in the queue..." message - when the server is experiencing heavy load, like when generating chunks.

**Comment by JustRed23** [comment]
This is not really an error though, its a general warning. These do appear when the world is loading but they should go away after the server has finished booting.

**Comment by JustRed23** [comment]
This might be caused by your server being under a high load from other mods

**Comment by Chisasfam** [comment]
> This is not really an error though, its a general warning. These do appear when the world is loading but they should go away after the server has finished booting.

The server doesnt open tho :') it crashes after, I had to remove VS2

**Comment by Chisasfam** [comment]
> That would probably point to your server running on old hardware / not having enough resources to properly boot VS2

The server is hosted on Bisect and is 10gigs it should be enough, we only started having this problem when we changed to magma. before we moved to magma it was 4gb on a normal forge server and it worked fine lol

**Comment by Chisasfam** [comment]
> I have the exact same issue _without_ Magma, or any other Bukkit-on-Forge mods. In my case, it's likely because I have approximately 500 mods installed in my own private modpack ([mod list](https://gist.github.com/unilock/79ac54321a731426092679778234b5c1)). I, personally, am not too concerned about this issue at the moment, since I intend to remove the majority of those mods "soon", which should hopefully be rid of the problem. Though if you'd like me to test with what I have now, I certainly can. In any case, I'll definitely report back if I continue running into this problem afterwards.
> 
> Of note: I usually run into what the OP describes - that is, the server crashing after the repeated "Too many frames in the queue..." message - when the server is experiencing heavy load, like when generating chunks.

what would you suggest because magma is buggy but we need plugins for the server to actually run with economy and kits and ranks. :')

**Comment by Rubydesic** [comment]
Magma is not supported sorry
