### ISSUE TITLE
Krunch cause memory leak when new world loads

### ISSUE THREAD

**Issue by Ranpoes** [ValkyrienSkies/Valkyrien-Skies-2#487]
We changed part of VS2 to make it compatible with some multi-world mods/plugins, and we found problems that theres lot of non-heap memory leak after the reload of the world. The picture bellow shows that we have a -Xmx flag for 4G heap memory limitation, but actually ths server used totally 22GB. We analyzed the jvm memory dump which shows theres not much GC during server running.
![14a211208f6cdb0f](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/48944068/d9d4b1a2-ac43-44f6-9065-75eda1e70133)
We turned off the Krunch by simply throw Exception in physicsEngine initialization, which lead to using DummyPhysicsWorldReference instead of native methods, and theres no more memory leak. But the physics seem not work any more.
```
init {
        // Try creating the physics engine
        physicsEngine = try {
            val temp = KrunchBootstrap.createKrunchPhysicsWorld()
            //here we go to DummyPhysicsWorld
            throw RuntimeException()
            // Apply physics engine settings
            KrunchBootstrap.setKrunchSettings(
                temp,
                VSCoreConfig.SERVER.physics.makeKrunchSettings()
            )
            temp
        } catch (e: Exception) {
            // Fallback to dummy physics engine if Krunch isn't supported
            e.printStackTrace()
            isUsingDummy = true
            DummyPhysicsWorldReference()
        }
    }
```
We found that there is a native method called deletePhysicsWorldResources() which seems can free the system memory resource, but it will lead to the only physicsEngine down and crash the server. Though we cant know the implementation of those DLLs, is there any chance to add a method for freeing the memory used by the given dimensions?
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/48944068/83dc4385-5e9d-4053-85d9-d99a0fede0b9)

**Comment by StewStrong** [comment]
So I actually found this same memory leak a few days ago when I ran Krunch unit tests with valgrind. Basically what's happened is that internally I was storing a Map<ChunkPos, Chunk*>, and the default destructor for the voxel shape wouldn't actually free the chunk pointers.

I've since fixed this in Krunch with a custom destructor, but I haven't updated it in vs-core yet. I'll do that soon.

**Comment by StewStrong** [comment]
This should be fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/49cdf4c0e96c03749f8b9bf2a51401434072284f

This build has the fix in it, and should fix the memory leak.

https://app.circleci.com/pipelines/github/ValkyrienSkies/Valkyrien-Skies-2/331/workflows/941d399c-14c3-4590-b02f-8a66dc70e3b4/jobs/499/artifacts
