### ISSUE TITLE
Server dead freeze at some point

### ISSUE THREAD

**Issue by Proxwian** [ValkyrienSkies/Valkyrien-Skies-2#521]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Server dead freezed at some point

### Issue reproduction

Run VS 1.18.2 on dedicated server with 10+ players online for 1-2 days

### Logs

https://mclo.gs/CGc1zVS

**Comment by Proxwian** [comment]
Can't test without all mods just because I can't run server just with VS having 10 players online at moment, sorry.

**Comment by Rubydesic** [comment]
VS2 generally doesn't support forge/bukkit hybrid servers, but some users have had success with [Arclight](https://github.com/IzzelAliz/Arclight)

Additionally, 
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS and addons, and then create a new issue.
