### ISSUE TITLE
How do I request an unban on the discord server?

### ISSUE THREAD

**Issue by Olibobs1** [ValkyrienSkies/Valkyrien-Skies-2#750]
I'm unsure on how to request an unban on the VS discord server, I understand I was banned for a fair reason (n-word in pronouns), but in my defence I had done it for a small joke privately with my friends, and had forgotten about it, I have since changed it and am willing to accept any restrictions such as being muted. I am only wanting access to the mods for a bit of fun with my friends. 

I cant find anywhere else to go with this issue so guidance is appreciated.

if you can help me: 

user id: 730510839810883684
account name: Olibobs1#7372

if you want to ask me any questions I don't mind and am willing to follow any requests :)

**Comment by ewoudje** [comment]
You made a appeal it was rejected don't go to github for this.

l bozo

**Comment by RatDotRaw** [comment]
Sir,

I have perused your missive of supplication concerning your expulsion from the VS discord server. I must avow that I am rather astonished by your impudence to solicit readmission after your flagrant breach of the rules of propriety and courtesy. You acknowledge that you employed a most abhorrent and coarse term in your pronouns, which you aver was a trifling amusement among your friends. However, you seem to neglect the fact that such language is not only intolerable in refined society, but also hurtful to the honour and sensibilities of others who may have seen or heard it. You also evince no contrition for your actions, as you manifest your wish to access the mods for a bit of fun with your friends.

I lament to inform you that your supplication has been rejected, and your expulsion persists in effect. I entreat you to ponder on your behaviour and learn from your error, rather than continuing in your indiscretion. I also counsel you to desist from contacting me or any other moderator again, as your letters are unwelcome and will be disregarded. I have nothing more to communicate to you, except that I hope you will reform your ways and become a better person.

I remain,

Your obedient servant,

Some random guy who isn't even a moderator.

**Comment by StafDierickx** [comment]
Sir or Madam,

I have examined your epistle of entreaty regarding your removal from the VS discord server. I must declare that I am rather confounded by your temerity to request restoration after your blatant transgression of the rules of decency and respect. You concede that you used a most detestable and rude term in your pronouns, which you state was a slight diversion among your companions. However, you seem to overlook the fact that such language is not only unsuitable in polite society, but also harmful to the reputation and feelings of others who may have observed or heard it. You also display no regret for your actions, as you reveal your desire to access the mods for a bit of fun with your friends.

I grieve to inform you that your entreaty has been spurned, and your removal endures in effect. I beseech you to contemplate on your conduct and learn from your blunder, rather than persisting in your imprudence. I also recommend you to cease from contacting me or any other moderator again, as your epistles are unwelcome and will be neglected. I have nothing more to impart to you, except that I hope you will amend your ways and become a better person.

I remain,

Your faithful servant,

Not a moderator.

**Comment by illucc** [comment]
Dear [username]

Thank you for showing interest in reintegrating with the Valkyrien Skies 2 community and changing your previous ways. After careful consideration though, thermonuclear weapon.

-Illuc

**Comment by RatDotRaw** [comment]
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/33757638/eb771d1a-ea3f-469c-91ea-6c6fec99f537)

**Comment by gjunnila** [comment]
I'm unsure on how to request an unban on the VS discord server, I understand I was banned for a fair reason (n-word in pronouns), but in my defence I had done it for a small joke privately with my friends, and had forgotten about it, I have since changed it and am willing to accept any restrictions such as being muted. I am only wanting access to the mods for a bit of fun with my friends.

I cant find anywhere else to go with this issue so guidance is appreciated.

if you can help me:

user id: 730510839810883684
account name: Olibobs1#7372

if you want to ask me any questions I don't mind and am willing to follow any requests :)

**Comment by Olibobs1** [comment]
I am a little lost, the words be to fancy for me lads.
